plugins {
	alias(libs.plugins.fabric.loom.remap)
	id 'maven-publish'
}

loom {
	serverOnlyMinecraftJar()
}

repositories {
	maven {
		name = "Ladysnake Mods"
		url = "https://maven.ladysnake.org/releases"
	}
}

dependencies {
	minecraft(libs.minecraft)
	mappings loom.officialMojangMappings()
	modImplementation(libs.fabric.loader)
	modImplementation(libs.fabric.api)

	implementation project(path: ':common', configuration: 'namedElements')
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("${rootDir}/LICENSE") {
		rename { "${it}_$projectName" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
		// Add repositories to publish to here.
	}
}
