pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = "Maven Central HTTPS"
			url "https://repo1.maven.org/maven2"
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid
rootProject.name = 'excentric'

include 'common'
include 'fabric'
