plugins {
    alias(libs.plugins.fabric.loom.remap)
}

loom {
	serverOnlyMinecraftJar()
}

repositories {
	maven {
		name = "Ladysnake Mods"
		url = "https://maven.ladysnake.org/releases"
	}
}

dependencies {
	minecraft(libs.minecraft)
	mappings loom.officialMojangMappings()
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
