plugins {
	alias(libs.plugins.fabric.loom.remap)
}

loom {
	serverOnlyMinecraftJar()

	// Remove the run configurations from the common module.
	runs {
		removeIf { true }
	}
}

repositories {
	maven {
		name = "Spongepowered"
		url = "https://repo.spongepowered.org/repository/maven-public"
	}
}

dependencies {
	minecraft(libs.minecraft)
	mappings loom.officialMojangMappings()
	compileOnly(libs.mixin)
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
